# Generated by Django 3.0.5 on 2020-05-05 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hibpkey', models.TextField(blank=True, max_length=500)),
                ('googleapikey', models.TextField(blank=True, max_length=500)),
                ('macapikey', models.TextField(blank=True, max_length=500)),
                ('emailkey', models.TextField(blank=True, max_length=500)),
                ('virustotalkey', models.TextField(blank=True, max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
