# Generated by Django 3.0.5 on 2020-05-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='clusterjson',
            field=models.FileField(default='data.json', upload_to=''),
        ),
    ]
