# Generated by Django 3.0.5 on 2020-05-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0002_profile_clusterjson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='clusterjson',
            field=models.FileField(default='data.json', upload_to='json/'),
        ),
    ]
