# Generated by Django 3.0.5 on 2020-05-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0002_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='emailkey',
            new_name='hlrlookupkey',
        ),
        migrations.AddField(
            model_name='profile',
            name='ipstackkey',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
