# Generated by Django 3.0.3 on 2020-05-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0004_auto_20200505_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hunterkey',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
