# Generated by Django 3.0.3 on 2020-05-11 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0005_profile_hunterkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='builtwithkey',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
