# Generated by Django 3.0.5 on 2020-06-15 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0005_auto_20200615_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ratelimit',
        ),
    ]
