# Generated by Django 3.0.5 on 2020-05-11 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0005_profile_hunterkey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='metaimage',
        ),
    ]
