# Generated by Django 3.0.5 on 2020-05-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0006_auto_20200511_0538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='googleapikey',
            new_name='googlemapapikey',
        ),
        migrations.AlterField(
            model_name='profile',
            name='metaimage',
            field=models.ImageField(default='default.jpg', upload_to='metadata/'),
        ),
    ]
