# Generated by Django 3.0.3 on 2020-05-11 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0008_remove_profile_wappalyzerkey'),
        ('webgui', '0007_auto_20200511_0844'),
    ]

    operations = [
    ]
