# Generated by Django 3.0.5 on 2020-06-16 03:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0008_auto_20200615_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resetdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 16, 3, 43, 45, 171091)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ratelimit',
            field=models.IntegerField(default=100, editable=False),
        ),
    ]
