# Generated by Django 3.0.3 on 2020-05-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0009_merge_20200511_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='censyskey',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='shodankey',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
