# Generated by Django 3.0.3 on 2020-05-12 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0011_profile_censyssecret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='censyskey',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='censyssecret',
        ),
    ]
