# Generated by Django 3.0.5 on 2020-06-16 04:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0011_auto_20200616_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='resetdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 16, 4, 15, 44, 785705), editable=False),
        ),
    ]
