# Generated by Django 3.0.5 on 2020-06-16 04:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0012_auto_20200616_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='resetdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 16, 4, 18, 42, 791844), editable=False),
        ),
    ]
