# Generated by Django 3.0.3 on 2020-05-12 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0012_auto_20200512_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='shodankey',
        ),
    ]
