# Generated by Django 3.0.5 on 2020-06-16 04:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0013_auto_20200616_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ratelimit',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='resetdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 16, 4, 19, 6, 583882), editable=False),
        ),
    ]
