# Generated by Django 3.0.3 on 2020-05-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0013_remove_profile_shodankey'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='shodankey',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
