# Generated by Django 3.0.3 on 2020-05-14 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0014_profile_shodankey'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='emailrepkey',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
