# Generated by Django 3.0.5 on 2020-05-15 06:03

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0016_profile_victimips'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='victimips',
        ),
        migrations.AddField(
            model_name='profile',
            name='trackdata',
            field=jsonfield.fields.JSONField(default=None),
            preserve_default=False,
        ),
    ]
