# Generated by Django 3.0.3 on 2020-05-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0016_profile_victimips'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='c_user',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='xs',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
