# Generated by Django 3.0.5 on 2020-05-15 07:10

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0018_auto_20200515_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='trackdata',
            field=jsonfield.fields.JSONField(blank=True),
        ),
    ]
