# Generated by Django 3.0.5 on 2020-06-16 04:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0019_auto_20200616_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='resetdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 16, 4, 33, 55, 252898, tzinfo=utc)),
        ),
    ]
