# Generated by Django 3.0.5 on 2020-05-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0019_auto_20200515_0710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='trackdata',
        ),
        migrations.AddField(
            model_name='profile',
            name='victimlatitude',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='victimlocip',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='victimlongitutde',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='victimpublicip',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
