# Generated by Django 3.0.5 on 2020-05-15 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0020_auto_20200515_0852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='victimlongitutde',
            new_name='victimlongitude',
        ),
    ]
