# Generated by Django 3.0.3 on 2020-05-15 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0021_auto_20200515_0909'),
        ('webgui', '0017_auto_20200515_0940'),
    ]

    operations = [
    ]
