# Generated by Django 3.0.3 on 2020-05-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0022_merge_20200515_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='victimips',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
