# Generated by Django 3.0.5 on 2020-05-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0023_profile_victimips'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='darkmode',
            field=models.BooleanField(default=False),
        ),
    ]
