# Generated by Django 3.0.5 on 2020-06-16 04:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0027_auto_20200616_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='resetdate',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 16, 4, 42, 14, 477618)),
        ),
    ]
