# Generated by Django 3.0.5 on 2020-06-16 04:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0032_auto_20200616_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='resetdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
