# Generated by Django 3.0.8 on 2020-07-18 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0036_profile_victimuseragent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='darkmode',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='ratelimit',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='resetdate',
        ),
    ]
