# Generated by Django 3.0.8 on 2020-07-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0037_auto_20200718_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='clusterjson',
            field=models.FileField(default='cluster.json', upload_to='json/'),
        ),
    ]
