# Generated by Django 3.0.8 on 2020-08-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webgui', '0038_auto_20200728_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='case',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
